version: '3'
services:
   db:
      image: postgres
      restart: always
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin
         POSTGRES_DB: copasty
      volumes:
         - copastyPG:/var/lib/postgresql/data
      ports:
         - 5432:5432
   cache:
      image: redis
      restart: always
      command: /bin/sh -c "redis-server --requirepass redispassword"
      ports:
         - 6379:6379
      volumes:
         - copastyRS:/data
volumes:
   copastyPG:
   copastyRS:
